name: "HashBlog"
description: "Generate an automated hashnode blog for every commit!"
inputs:
  blog-domain:
    description: "The hashnode domain where your blog would be posted."
    required: true
  series-slug:
    description: "The series in which you want to add your blog to."
  add_tags:
    description: "Whether to add automatic generated tags to the blog post or not."
    default: false
  tags:
    description: "Upto 5 tags slugs which you want to add to your blog."
# outputs:
#   time: # id of output
#     description: "The time we greeted you"
runs:
  using: "node20"
  main: "index.js"
