name: "Commit Blog Generator"
description: "Generate an automated blog for every commit!"
inputs:
  blog-domain:
    description: "The domain where the blog would be posted."
    required: true
# outputs:
#   time: # id of output
#     description: "The time we greeted you"
runs:
  using: "node20"
  main: "index.js"
